# .scrutinizer.yml

filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        code_rating: true
        duplication: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    environment:
        php:
            version: 7.0.7
tools:
    external_code_coverage: true
